export const GET_WEATHER_CURRENTLY = "GET_WEATHER_CURRENTLY";
export const GET_WEATHER_HOURLY = "GET_WEATHER_HOURLY";
export const SET_LOADING = "SET_LOADING";
export const SET_DISABLED_BUTTON = "SET_DISABLED_BUTTON";
