export const GET_WEATHER_CURRENTLY = "GET_WEATHER_CURRENTLY";
export const GET_WEATHER_HOURLY = "GET_WEATHER_HOURLY";
export const GET_WEATHER_CITY = "GET_WEATHER_CITY";
export const SET_LOADING = "SET_LOADING";
export const SET_DISABLED_BUTTON = "SET_DISABLED_BUTTON";
export const GET_COUNTRY_WEATHER_INFO = "GET_COUNTRY_WEATHER_INFO";
